#!/usr/bin/env python
# coding: utf-8



get_ipython().run_line_magic('matplotlib', 'inline')
import numpy as np
import pandas as pd
import matplotlib.pylab as pl
import ast
import re, ast



s = input("Input the string with 0 and 1\n") # string with bytes in one line
nbDays = int(input("Input number of days you want to fill\n")) #number of days in championship
nbTeams = 22 # number of teams in championship
nbStadiums = 22 # number of stadiums in championship

ls = re.sub('\s+', ',', s)
a = np.array(ast.literal_eval(ls)).reshape(nbTeams, nbStadiums, nbDays)




b = np.zeros(a.shape[0] * a.shape[2], dtype='object').reshape(a.shape[0], a.shape[2])
d = {'team_home': [], 'team_opponent': [], 'day': []}
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            if a[i][j][k]:
                d['team_home'].append(i + 1)
                d['team_opponent'].append(j + 1)
                d['day'].append(k + 1)              
                
                
d = pd.DataFrame(d)
d = d.to_numpy()
d = d.ravel()
_dict = {}
for A, B in zip([i for i in [-22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 1, 2, 3, 4, 5, 6,7 ,8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]], '-АДМ -АМР -СИБ -БАР -АВГ -СЮЛ -АВТ -ММГ -ТРК -АКБ -НХК -КРС -СПР -СОЧ -ТОР -ДИН -ЛОК -СЕВ -СКА -ВИТ -ДМН -ЦСК АДМ АМР СИБ БАР АВГ СЮЛ АВТ ММГ ТРК АКБ НХК КРС СПР СОЧ ТОР ДИН ЛОК СЕВ СКА ВИТ ДМН ЦСК'.split(" ")):
    _dict[A] = B
    
for i in range(len(d) - 2):
    if i % 3 == 0:
        b[d[i] - 1][d[i + 2] - 1] = f"{_dict[d[i + 1]]}"
        b[d[i + 1] - 1][d[i + 2] - 1] = f"-{_dict[d[i]]}"




    
nx = a.shape[2]
ny = a.shape[0]
x_axis = [i for i in range(1, a.shape[2] + 1)]
y_axis = 'АДМ АМР СИБ БАР АВГ СЮЛ АВТ ММГ ТРК АКБ НХК КРС СПР СОЧ ТОР ДИН ЛОК СЕВ СКА ВИТ ДМН ЦСК'.split(" ")
pl.figure()


tb = pl.table(cellText=b, loc=(0,0), rowLabels=y_axis, colLabels=x_axis, cellLoc='center')



for i in range(0, a.shape[2]):
    tb.get_celld()[(0,i)].set_facecolor("#56b5fd")
  
tc = tb.properties()['child_artists']

for cell in tc: 
    cell.set_height(1)
    cell.set_width(1)


        
tb.set_fontsize(50)
ax = pl.gca()
ax.set_xticks([])
ax.set_yticks([])
ax.set_ylabel("Команда")
ax.set_xlabel("День")
